#ifndef SZIPROCESSOR_H
#define SZIPROCESSOR_H


#include "dataprocessor.h"

class SziDataProcessor : public DataProcessor
{
    Q_OBJECT
    QString file_header ="\t\t\t\t\t/*WARNING !!! -> THIS FILE IS GENERATED AUTOMATICALLY. DO NOT EDIT THIS FILE MANUALLY <- WARNING !!!*/\r\n\r\n\
typedef struct\r\n\
{\r\n\
    int NUMBER_MODUL;\r\n\
    CPU_NUM NUMBER_CPU;\r\n\
    PO_NUM_TYPE NUMBER_PO;\r\n\
    unsigned int CHECKSUM;\r\n\
}PO_CHECKSUM;\r\n\
\r\n\
const PO_CHECKSUM po_info[]  =\r\n\
{\r\n";
public:
    explicit SziDataProcessor(Manager* _sre,QObject *parent = nullptr);
    void process();
signals:
private:
    Manager* sre;
    int getCpu(size_t la);
};

#endif // SZIPROCESSOR_H
